### PR TITLE
Fix incorrect SpaceAfter=No

### PR DESCRIPTION
**Pull request by EmilStenstrom**
Incorrect text:
"märka dem ( gälleräven valkuverten)"

Corrected text:
"märka dem (gäller även valkuverten)"

This is fixed simply by moving the SpaceAfter=No one token earlier in the sentence.

### CODE REVIEW

**Comment by dan-zeman** [comment]
Sorry, we do not accept pull requests against the master branch. Please see http://universaldependencies.org/release_checklist.html#repository-branches for more details. Thanks

Dan

**Comment by EmilStenstrom** [comment]
@dan-zeman I've changed this PR to be against to the dev branch.

**Comment by dan-zeman** [comment]
OK, thanks. I am leaving it here for the UD_Swedish-Talbanken maintainers to take care of it. (They have also set "Contributing: elsewhere" in the README file, so maybe it will go other ways at the end of the day. But in any case, thanks for the report!)

**Comment by EmilStenstrom** [comment]
I'm pinging @jnivre, as he is the contact in the metadata. Where should I be contributing this fix?

**Comment by jnivre** [comment]
@EmilStenstrom Sorry for the slow response (I am on vacation) and thanks for reporting this error. Swedish-Talbanken is generated automatically from the old Talbanken annotation by a sequence of scripts that converts to UD and implements a number of corrections that we have accumulated over the years. Hence, the way to fix this error is to make sure that it is fixed by a script (or, rather, make sure that it is not introduced by a script, since I suspect that this is due to an incorrectly implemented manual correction). I will make sure to add this to the list of things to fix before the next release.

**Comment by EmilStenstrom** [comment]
@jnivre Excellent. Thanks for the quick reply!

**Pull request closed without merging**
